from kaptan.ui_avatar import *
from kaptan.ui_menu import *
from kaptan.ui_mouse import *
from kaptan.ui_other import *
from kaptan.ui_pm import *
from kaptan.ui_summary import *
from kaptan.ui_theme import *
from kaptan.ui_wallpaper import *
from kaptan.ui_welcome import *